import "dotenv/config";
// import { generateFakeDataSets } from "./generateFakeDataSet.js";
import axios from "axios";

const seedDataSet = () => {
  // const addDataSet = await axios.post(`${process.env.SERVER_URL}/dataset`, seedDataSet)
  const dataSet = [
    {
      projectName: "Hydration Stations",
      items: [
        {
          image: "Tarps.png",
          description: "Tarps",
          weekly: 60,
          monthly: 150,
          quarterly: 200,
          current: 1160,
          goal: 1850,
          lastUpdate: "Just Now",
        },
        {
          image: "BottledWater.png",
          description: "Bottled Water",
          weekly: 80,
          monthly: 150,
          quarterly: 200,
          current: 1170,
          goal: 1590,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "Hygiene1.png",
          description: "Hygiene Kits",
          weekly: 20,
          monthly: 120,
          quarterly: 210,
          current: 1460,
          goal: 1520,
          lastUpdate: "Last Week",
        },
        {
          image: "socks.png",
          description: "Clothing (other)",
          weekly: 40,
          monthly: 140,
          quarterly: 210,
          current: 1280,
          goal: 1870,
          lastUpdate: "Just Now",
        },
      ],
    
    },
    {
      projectName: "Spring Fling",
      items: [
        {
          image: "help2.png",
          description: "Beanies",
          weekly: 100,
          monthly: 140,
          quarterly: 210,
          current: 1230,
          goal: 1590,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "hands.png",
          description: "Gloves",
          weekly: 50,
          monthly: 130,
          quarterly: 220,
          current: 2440,
          goal: 2870,
          lastUpdate: "Last Week",
        },
        {
          image: "thermals.png",
          description: "Thermals",
          weekly: 70,
          monthly: 250,
          quarterly: 200,
          current: 2060,
          goal: 2690,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "SleepingBags.png",
          description: "Sleeping Bags",
          weekly: 30,
          monthly: 220,
          quarterly: 220,
          current: 2240,
          goal: 2990,
         lastUpdate: "5 Days Ago",
        },
        {
          image: "Tarps.png",
          description: "Tarps",
          weekly: 80,
          monthly: 240,
          quarterly: 220,
          current: 2430,
          goal: 2760,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "Tents.png",
          description: "Tents",
          weekly: 50,
          monthly: 240,
          quarterly: 200,
          current: 2200,
          goal: 2820,
          lastUpdate: "Last Week",
        },
        {
          image: "BottledWater.png",
          description: "Bottled Water",
          weekly: 200,
          monthly: 250,
          quarterly: 220,
          current: 2090,
          goal: 1660,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "Hygiene1.png",
          description: "Hygiene Kits",
          weekly: 20,
          monthly: 130,
          quarterly: 210,
          current: 1470,
          goal: 1910,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "socks.png",
          description: "Clothing (other)",
          weekly: 80,
          monthly: 130,
          quarterly: 200,
          current: 1430,
          goal: 1980,
         lastUpdate: "5 Days Ago",
        },
      ],
    },
    {
      projectName: "Warm Up for Winter",
      items: [
        {
          image: "blankets.png",
          description: "Blankets",
          weekly: 30,
          monthly: 140,
          quarterly: 210,
          current: 1150,
          goal: 1920,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "Clients1.png",
          description: "Winter Coats",
          weekly: 50,
          monthly: 120,
          quarterly: 210,
          current: 1190,
          goal: 2000,
          lastUpdate: "Last Week",
        },
        {
          image: "help2.png",
          description: "Beanies",
          weekly: 30,
          weekly: 30,
          monthly: 120,
          quarterly: 210,
          current: 1140,
          goal: 1990,
         lastUpdate: "5 Days Ago",
        },
        {
          image: "hands.png",
          description: "Gloves",
          weekly: 50,
          monthly: 120,
          quarterly: 210,
          current: 1190,
          goal: 2000,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "thermals.png",
          description: "Thermals",
          weekly: 30,
          monthly: 130,
          quarterly: 255,
          current: 1425,
          goal: 1915,
          lastUpdate: "Last Week",
        },
        {
          image: "SleepingBags.png",
          description: "Sleeping Bags",
          weekly: 65,
          monthly: 145,
          quarterly: 255,
          current: 1465,
          goal: 1895,
         lastUpdate: "5 Days Ago",
        },
        {
          image: "Tarps.png",
          description: "Tarps",
          weekly: 25,
          monthly: 135,
          quarterly: 215,
          current: 1580,
          goal: 1930,
          lastUpdate: "Last Week",
        },
        {
          image: "Tents.png",
          description: "Tents",
          weekly: 40,
          monthly: 150,
          quarterly: 200,
          current: 1140,
          goal: 1920,
         lastUpdate: "5 Days Ago",
        },
        {
          image: "BottledWater.png",
          description: "Bottled Water",
          weekly: 60,
          monthly: 110,
          quarterly: 210,
          current: 1250,
          goal: 1990,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "Hygiene1.png",
          description: "Hygiene Kits",
          weekly: 90,
          monthly: 120,
          quarterly: 200,
          current: 1230,
          goal: 1890,
         lastUpdate: "5 Days Ago",
        },
        {
          image: "socks.png",
          description: "Clothing (other)",
          weekly: 10,
          monthly: 120,
          quarterly: 200,
          current: 1260,
          goal: 1940,
          lastUpdate: "Last Week",
        },
      ],
    },
    {
      projectName: "All in For Fall",
      items: [
        {
          image: "blankets.png",
          description: "Blankets",
          weekly: 36,
          monthly: 145,
          quarterly: 215,
          current: 1155,
          goal: 1925,
          lastUpdate: "Last Week",
        },
        {image: "Clients1.png",
          description: "Winter Coats",
          weekly: 55,
          monthly: 125,
          quarterly: 215,
          current: 1195,
          goal: 2155,
          lastUpdate: "Last Week",
        },
        {
          image: "help2.png",
          description: "Beanies",
          weekly: 35,
          weekly: 35,
          monthly: 125,
          quarterly: 215,
          current: 1145,
          goal: 2295,
          lastUpdate: "Last Week",
        },
        {
          image: "hands.png",
          description: "Gloves",
          weekly: 55,
          monthly: 125,
          quarterly: 215,
          current: 1795,
          goal: 2555,
         lastUpdate: "5 Days Ago",
        },
        {
          image: "thermals.png",
          description: "Thermals",
          weekly: 35,
          monthly: 135,
          quarterly: 255,
          current: 1425,
          goal: 1915,
         lastUpdate: "5 Days Ago",
        },
        {
          image: "SleepingBags.png",
          description: "Sleeping Bags",
          weekly: 65,
          monthly: 145,
          quarterly: 255,
          current: 1465,
          goal: 1895,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "Tarps.png",
          description: "Tarps",
          weekly: 25,
          monthly: 135,
          quarterly: 215,
          current: 1585,
          goal: 1935,
          lastUpdate: "3 Days Ago",
        },
        {
          image: "Tents.png",
          description: "Tents",
          weekly: 45,
          monthly: 155,
          quarterly: 255,
          current: 1145,
          goal: 1925,
         lastUpdate: "5 Days Ago",
        },
        {
          image: "BottledWater.png",
          description: "Bottled Water",
          weekly: 65,
          monthly: 115,
          quarterly: 215,
          current: 1255,
          goal: 1995,
          lastUpdate: "Last Week",
        },
        {
          image: "Hygiene1.png",
          description: "Hygiene Kits",
          weekly: 90,
          monthly: 120,
          quarterly: 200,
          current: 1230,
          goal: 1890,
          lastUpdate: "Last Week",
        },
        {
          image: "socks.png",
          description: "Clothing (other)",
          weekly: 10,
          monthly: 120,
          quarterly: 200,
          current: 1260,
          goal: 1940,
         lastUpdate: "5 Days Ago",
        },
      ],
    },
  ];
  console.log("seedDataSet", seedDataSet);

  dataSet.map(async (data) => {
    const addDataSet = await axios.post(
      `${process.env.SERVER_URL}/dataset`,
      data
    );
    console.log("addDataSet", addDataSet.data);
  });
};

seedDataSet();
